# Site settings
author: Catherine Smiley
title: Boot Camp Journey
header-img: img/home-bg.png
email: catherinesmiley@gmail.com
copyright_name: Catherine Smiley
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School Software Engineering Boot Camp
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  catherinesmiley

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
